### ISSUE TITLE
列举并解释你知道的选择器类型？

### ISSUE THREAD

**Issue by HaofangLiu** [HaofangLiu/interview#21]
## 元素选择器(标签选择器)
`a{ text-decoration:none }`
`body{ font-size:14px }`

## id选择器
`#id{border:1px solid black}`

## 类选择器
`.active{color:red}`

## 通用选择器
`* {margin:0; padding:0}`

## 属性选择器
* [attr]选择包含 attr 属性的所有元素，不论 attr 的值为何。
* [attr=val] 仅选择 attr 属性被赋值为 val 的所有元素。
```css
[disabled] {
border: 1px solid #ccc;
}
[data-color=“gray”] {
color: #666;
}
```
