### ISSUE TITLE
如何清除浮动

### ISSUE THREAD

**Issue by HaofangLiu** [HaofangLiu/interview#40]
```css
.clearfix:after {
            content: '';
            display: block;
            clear: both;
        }
```
题目来自饥人谷
